# Generated by Django 4.0.4 on 2022-05-15 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=10)),
                ('opening_count', models.IntegerField(default=1)),
                ('location', models.TextField()),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keyskills', models.TextField()),
                ('job_description', models.TextField()),
                ('employment_type', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('resume', models.FileField(upload_to='')),
                ('reviewed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.jobs')),
            ],
        ),
    ]
