# Generated by Django 4.0.4 on 2022-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_application_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
